/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adt.linkedin.gui;

import adt.linkedin.model.*;
import adt.linkedin.services.UserService;
import adt.linkedin.tools.Utils;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dev
 */
public class JFrameUser extends javax.swing.JFrame {

    final User user;
    final UserService controller;

    /**
     * Creates new form User
     *
     * @param user
     */
    public JFrameUser(User user) {
        this.user = user;
        controller = new UserService();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        this.jPanel1.setBounds(2, 2, JFrame.MAXIMIZED_HORIZ, JFrame.MAXIMIZED_VERT);
        fillTable(jTableAcademicInfo, 1);
        fillTable(jTableSkills, 2);
        fillTable(jTableExperience, 3);
        this.jButton1.setBackground(Utils.PURPLE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuConfirmation = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanelUser = new javax.swing.JPanel();
        jLabelUserPic = new javax.swing.JLabel();
        jLabelHeader = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSkills = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAcademicInfo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableExperience = new javax.swing.JTable();
        jLabelLogOut = new javax.swing.JLabel();
        jLabelCandidatures = new javax.swing.JLabel();
        jLabelDelete = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setPreferredSize(this.getPreferredSize());

        jPanelUser.setBackground(new java.awt.Color(255, 255, 255));
        jPanelUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jPanelUser.setPreferredSize(this.jPanel1.getPreferredSize());
        jPanelUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUserPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/defaultpic.png"))); // NOI18N
        jLabelUserPic.setText("jLabel2");
        jLabelUserPic.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 102, 255)));
        jPanelUser.add(jLabelUserPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 91, 91));

        jLabelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image.png"))); // NOI18N
        jPanelUser.add(jLabelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 960, 90));

        jLabelUserName.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("User");
        jPanelUser.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 52, -1));

        jLabelDescription.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(153, 153, 153));
        jLabelDescription.setText("Description");
        jPanelUser.add(jLabelDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 167, 57));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 102, 255), null));

        jTableSkills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Skills"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSkills.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableSkills);
        if (jTableSkills.getColumnModel().getColumnCount() > 0) {
            jTableSkills.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanelUser.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 420, 196));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 102, 255), null));

        jTableAcademicInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "AcademicInfo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAcademicInfo.setAutoscrolls(false);
        jTableAcademicInfo.setGridColor(new java.awt.Color(255, 255, 255));
        jTableAcademicInfo.setSelectionBackground(new java.awt.Color(153, 102, 255));
        jTableAcademicInfo.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableAcademicInfo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableAcademicInfo);
        if (jTableAcademicInfo.getColumnModel().getColumnCount() > 0) {
            jTableAcademicInfo.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanelUser.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 420, 190));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 102, 255), null));

        jTableExperience.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Experience"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableExperience.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableExperience);
        if (jTableExperience.getColumnModel().getColumnCount() > 0) {
            jTableExperience.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanelUser.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 420, 220));

        jLabelLogOut.setText("Log Out");
        jLabelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseExited(evt);
            }
        });
        jPanelUser.add(jLabelLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 110, 40));

        jLabelCandidatures.setText("My Candidatures");
        jLabelCandidatures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCandidaturesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCandidaturesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCandidaturesMouseExited(evt);
            }
        });
        jPanelUser.add(jLabelCandidatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, 50));

        jLabelDelete.setText("Delete Account");
        jPanelUser.add(jLabelDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 102, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(499, 499, 499)
                .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280)
                .addComponent(jButton1)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2000, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillTable(JTable table, int option) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        switch (option) {
            case 1: //AcademicInfo
                for (AcademicInfo info : controller.getUserAcademicInfo(user)) {
                    model.addRow(new String[]{info.toString()});
                }
                break;
            case 2: //Skills
                for (Skill skill : controller.getUserSkills(user)) {
                    model.addRow(new String[]{skill.toString()});
                }
                break;
            default: //Experience
                for (WorkExperience experience : controller.getUserLaboralExperience(user)) {
                    model.addRow(new String[]{experience.toString()});
                }
                break;
        }
        table.setModel(model);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Feed(user).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseEntered
        // TODO add your handling code here:
        Utils.mouseEntered(this.jLabelLogOut);
    }//GEN-LAST:event_jLabelLogOutMouseEntered

    private void jLabelLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseExited
        // TODO add your handling code here:
        Utils.mouseExited(this.jLabelLogOut);
    }//GEN-LAST:event_jLabelLogOutMouseExited

    private void jLabelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelLogOutMouseClicked

    private void jLabelCandidaturesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCandidaturesMouseEntered
        // TODO add your handling code here:
        Utils.mouseEntered(this.jLabelCandidatures);
    }//GEN-LAST:event_jLabelCandidaturesMouseEntered

    private void jLabelCandidaturesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCandidaturesMouseExited
        // TODO add your handling code here:
        Utils.mouseExited(this.jLabelCandidatures);
    }//GEN-LAST:event_jLabelCandidaturesMouseExited

    private void jLabelCandidaturesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCandidaturesMouseClicked
        // TODO add your handling code here:
        new JFrameCandidatures(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCandidaturesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUser(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelCandidatures;
    private javax.swing.JLabel jLabelDelete;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelUserPic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelUser;
    private javax.swing.JPopupMenu jPopupMenuConfirmation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAcademicInfo;
    private javax.swing.JTable jTableExperience;
    private javax.swing.JTable jTableSkills;
    // End of variables declaration//GEN-END:variables
}
